# Site settings
title: Jazzy Lazy AI
email: your-email@example.com
description: Where AI insights meet casual curiosity
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
