# Site settings
title: Jazzy Lazy AI
email: chicdevaugust@gmail.com
description: Deep talks, easy vibes
baseurl: "/ai-magazine"
url: "https://jazzy-lazy-cafe.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
